### ISSUE TITLE
For Developers

### ISSUE THREAD

**Issue by nschainblatt** [Group-Project-Team-4/Selenium#1]
Create a web-app using Flask that meets the the requirements in these links:
- https://www.softchalkcloud.com/lesson/serve/FS0GU719cgQqAr/html
- https://www.softchalkcloud.com/lesson/serve/sTU8zefIFcuLVp/html
- https://www.softchalkcloud.com/lesson/serve/aFbrBv78tETzyI/html

**Comment by Moonlight1211** [comment]
Web app is finished. Closing.
