### ISSUE TITLE
For Document Writers

### ISSUE THREAD

**Issue by nschainblatt** [Group-Project-Team-4/Selenium#2]
- Update README.md as for project progresses.
- RTM due on the 25th
Useful Links:
- https://www.softchalkcloud.com/lesson/serve/FS0GU719cgQqAr/html
- https://www.softchalkcloud.com/lesson/serve/sTU8zefIFcuLVp/html
- https://www.softchalkcloud.com/lesson/serve/aFbrBv78tETzyI/html
- (Example) https://www.softchalkcloud.com/lesson/serve/mIZsU7upqCBzLY/html

**Comment by Moonlight1211** [comment]
README.md is finished along with the rest of the lab. Closing.
