### ISSUE TITLE
README.md needs update

### ISSUE THREAD

**Issue by nschainblatt** [Group-Project-Team-4/Selenium#4]
Add instructions on setting up the selenium_tests.py module. Like Installing selenium with pip, adding chromedriver directory to path removes the need to have the path in the modules webdriver.Chrome(). Make sure to use all of markdown languages feautures to make people know what commands and such to use.

**Comment by GeorgieH20** [comment]
Just pushed through the changes, still work in progress. We can discuss during next meeting.

**Comment by Moonlight1211** [comment]
Finalized as of 1642b81192c76d159b47241f565aea0f2f45dca3. Closing issue.
