### ISSUE TITLE
Create Selenium Tests

### ISSUE THREAD

**Issue by DzHandsCode** [Group-Project-Team-4/Selenium#6]
Test are needed following functionalities:

Register - Cody Dietrich
Login - Nathaniel Schainblatt
Create new post - Nathaniel Schainblatt
Edit post - Cody Dietrich
Delete post -  Cody Dietrich
Logout - Nathaniel Schainblatt

**Comment by Moonlight1211** [comment]
Lab is finished and all of these tests should be implemented. Inactive issue, closing.
